# inventories/development/hosts.yml
all:
  children:
    development:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
      vars:
        environment: development
        domain_name: farmo.local
        ssl_enabled: false
        keycloak_admin_password: "admin123"
        postgres_password: "devpassword"